# Generated by Django 3.2.9 on 2023-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_product_cover_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_images',
            new_name='Product_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
